
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export interface VisionResult {
  imageUrl: string;
  poem: string;
  keyword: string;
}

export const generateVisionInOneGo = async (base64Image: string, name: string): Promise<VisionResult | null> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: base64Image.split(',')[1],
            },
          },
          { 
            text: `你是一位殿堂级浪漫主义艺术家。这张照片中的女孩叫“${name}”。
            请完成以下任务：
            1. 创作一首极致浪漫的四行诗，包含名字“${name}”，展现永恒、星光与独一无二。
            2. 根据这张照片的韵味，生成一张 16:9 比例的艺术大片。
            艺术风格要求：
            - 主题：基于原图的意境，将其重构成一个神圣、空灵的星空神殿或梦幻森林。
            - 视觉：4K 细腻画质、温暖的极光流动、电影级逆光、金色的粉尘粒子。
            - 情感：深情、守护、永恒。
            请先输出诗歌文字，随后生成对应的图像。` 
          }
        ]
      },
      config: {
        imageConfig: { aspectRatio: "16:9" }
      }
    });

    let imageUrl = '';
    let textContent = '';

    const candidate = response.candidates?.[0];
    if (!candidate) return null;

    // 严谨遍历所有 Part，提取文字和图像
    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
      } else if (part.text) {
        textContent += part.text;
      }
    }

    // 如果模型没给图，可能触发了安全机制或其他，这里返回 null 以便 App 层重试
    if (!imageUrl) {
      console.warn("No image generated by Gemini.");
      return null;
    }

    const poemLines = textContent.split('\n').map(l => l.trim()).filter(line => line.length > 2);
    const poem = poemLines.slice(0, 4).join('\n') || "在亿万星辰的重叠里，\n你是我唯一的引力。";

    return {
      imageUrl,
      poem,
      keyword: "永恒凝视"
    };
  } catch (error) {
    console.error("Masterpiece generation failed:", error);
    return null;
  }
};
